version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: task-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

app:
    build: .
    container_name: task-app
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "3000:3000"

volumes:
  postgres-data:
